# -----------------------------------------------------------------------------
# REPLICATED from the private shared repository (shared/python/html_sanitize.py).
# DO NOT EDIT HERE - changes will be overwritten by the next propagation run.
# Fix the master in the shared repository and re-propagate. See CONTRIBUTING.md.
# -----------------------------------------------------------------------------
"""Allow-list HTML sanitiser for untrusted fragments (LLM output, mainly).

Why this exists
---------------
The threat brief in `watch/src/digest.py` is generated by an LLM with web
search enabled, so its HTML is untrusted twice over: the prompt is written by
a scope owner, and a search result can carry an indirect injection. It used to
be filtered by replacing six literals (`<script`, `<iframe`, `<style`), which
does not see `<img onerror=…>` or `<svg onload=…>` at all — a deny-list over
HTML is structurally losing, since neither the event-handler set nor the
encodings can be enumerated.

Why not a library
-----------------
`bleach` announced end of life on 2026-06-05: "no future releases including for
security issues". Its successor `nh3` (Rust `ammonia` bindings) is the right
long-term answer, but the only published version, 0.3.6, pins ammonia 4.1.2,
which RUSTSEC-2026-0193 and RUSTSEC-2026-0213 affect — two mXSS/XSS bypasses,
the exact class this module defends against. The fix is on nh3's `main`,
unreleased. Revisit once 0.3.7 ships.

What this covers, and what it does not
--------------------------------------
Re-emits from an allow-list rather than trying to strip the bad parts, so
anything unknown disappears by construction: every attribute is dropped unless
named, which removes the whole `on*` family without enumerating it, and `href`
must be http(s).

It is NOT a spec-compliant HTML5 tokeniser — `html.parser` differs from a
browser on some malformed input, which is where mutation XSS lives. That is an
accepted trade-off here: the in-app render is already inside
`<iframe sandbox="">` with CSP `script-src 'self'`, so nothing executes there;
the emailed copy is the real exposure, and mail clients do not run JavaScript.
What matters in an email is that no phishing anchor and no spoofed markup
survives, which an allow-list does handle. Do not reuse this to sanitise HTML
destined for an unsandboxed browser context without revisiting that reasoning.
"""
from __future__ import annotations

from html import escape
from html.parser import HTMLParser
from urllib.parse import urlparse

# Formatting only. No embedding (img/svg/object/iframe), no style, no script,
# no form controls — the brief is prose, a list and the odd link.
_ALLOWED_TAGS: dict[str, frozenset[str]] = {
    "p": frozenset(),
    "br": frozenset(),
    "strong": frozenset(),
    "b": frozenset(),
    "em": frozenset(),
    "i": frozenset(),
    "u": frozenset(),
    "code": frozenset(),
    "pre": frozenset(),
    "ul": frozenset(),
    "ol": frozenset(),
    "li": frozenset(),
    "h3": frozenset(),
    "h4": frozenset(),
    "h5": frozenset(),
    "blockquote": frozenset(),
    "span": frozenset(),
    "div": frozenset(),
    "table": frozenset(),
    "thead": frozenset(),
    "tbody": frozenset(),
    "tr": frozenset(),
    "th": frozenset(),
    "td": frozenset(),
    "a": frozenset({"href", "title"}),
}

_VOID_TAGS = frozenset({"br"})

# Tags whose *content* must go too: dropping only the tag would paste the
# script body or the stylesheet into the document as visible text.
_DROP_CONTENT_TAGS = frozenset({"script", "style", "title", "textarea", "noscript"})

_SAFE_URL_SCHEMES = frozenset({"http", "https", "mailto"})


def safe_url(value: str) -> str:
    """Return `value` if it is a safe absolute or relative URL, else "".

    Rejects `javascript:`, `data:`, `vbscript:`, `file:` and anything else
    outside the allow-list. A scheme-less value (``/path``, ``page.html``) is
    kept: it cannot execute on its own.
    """
    v = (value or "").strip()
    if not v:
        return ""
    # Control characters and newlines are used to smuggle a scheme past naive
    # checks ("java\tscript:"); browsers strip them before parsing the URL.
    v = "".join(ch for ch in v if ord(ch) > 0x20 or ch == " ").strip()
    if not v:
        return ""
    try:
        scheme = (urlparse(v).scheme or "").lower()
    except ValueError:
        return ""
    if not scheme:
        return v if not v.startswith("//") else ""
    return v if scheme in _SAFE_URL_SCHEMES else ""


class _Sanitiser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._out: list[str] = []
        self._open: list[str] = []
        self._suppress_depth = 0

    # ── emission ────────────────────────────────────────────────────
    def handle_starttag(self, tag: str, attrs) -> None:
        if tag in _DROP_CONTENT_TAGS:
            self._suppress_depth += 1
            return
        if self._suppress_depth or tag not in _ALLOWED_TAGS:
            return
        allowed = _ALLOWED_TAGS[tag]
        kept = []
        for name, value in attrs:
            name = (name or "").lower()
            if name not in allowed:
                continue  # drops the whole on* family without enumerating it
            value = value or ""
            if name == "href":
                value = safe_url(value)
                if not value:
                    continue
            kept.append(f'{name}="{escape(value, quote=True)}"')
        rendered = " ".join([tag] + kept)
        self._out.append(f"<{rendered}>")
        if tag not in _VOID_TAGS:
            self._open.append(tag)

    def handle_endtag(self, tag: str) -> None:
        if tag in _DROP_CONTENT_TAGS:
            self._suppress_depth = max(0, self._suppress_depth - 1)
            return
        if self._suppress_depth or tag not in _ALLOWED_TAGS or tag in _VOID_TAGS:
            return
        if tag in self._open:
            # Close everything opened inside it, so the output stays balanced
            # even when the input was not.
            while self._open:
                current = self._open.pop()
                self._out.append(f"</{current}>")
                if current == tag:
                    break

    def handle_startendtag(self, tag: str, attrs) -> None:
        self.handle_starttag(tag, attrs)
        if tag not in _VOID_TAGS and self._open and self._open[-1] == tag:
            self._open.pop()
            self._out.append(f"</{tag}>")

    def handle_data(self, data: str) -> None:
        if self._suppress_depth:
            return
        self._out.append(escape(data, quote=False))

    # Comments, doctypes and processing instructions are dropped: conditional
    # comments and `<?xml`-style constructs are parsed differently across
    # renderers, which is a mutation vector for no benefit here.
    def handle_comment(self, data: str) -> None:
        return

    def handle_decl(self, decl: str) -> None:
        return

    def handle_pi(self, data: str) -> None:
        return

    def unknown_decl(self, data: str) -> None:
        return

    def result(self) -> str:
        while self._open:
            self._out.append(f"</{self._open.pop()}>")
        return "".join(self._out)


def sanitize_html(fragment: str) -> str:
    """Return `fragment` reduced to the allow-listed tags and attributes.

    Never raises: a fragment that cannot be parsed is returned fully escaped,
    which is the safe direction to fail in.
    """
    if not fragment:
        return ""
    parser = _Sanitiser()
    try:
        parser.feed(fragment)
        parser.close()
    except Exception:
        return escape(fragment, quote=False)
    return parser.result()
